### PR TITLE
Allow `path` specification in `pr_cookie()`

### PR DESCRIPTION
**Pull request by jtlandis**
This pull request will address #850 as the user will be able to specify the Path attribute of the cookie.

This attribute was already present in the main branches `res$setCookie` function, I was merely exposing this code. As such all edits were made such that default calls to `pr_cookie()` will not affect backwards compatibility.

I haven't yet added tests as I do not know how to test plumber endpoints in `testthat`.

Only one test failed when running `devtools::check()` and that was `test-serializer-htmlwidgets.R` testing "htmlwidgets get serialized properly".

PR task list:
- [x] Update NEWS
- [ ] Add tests
- [x] Update documentation with `devtools::document()`

### CODE REVIEW

**Comment by schloerke** [comment]
@jtlandis Could you sign the CLA above? Thank you!

**Comment by jtlandis** [comment]
I have signed the document, but I placed my name, not my github name into the form. It seems that if the submitted name cannot find the github user, then this pipeline fails.

I also cannot resign the form, as the form already has my associated github account as being approved. We can close this PR. If this is something the Devs would like, then I trust them to implement it into the code.

**Review by schloerke — COMMENTED** [review]
I'll make the necessary changes for merging. Np

**Review by schloerke — CHANGES_REQUESTED** [review]
Some minor changes need to be made. (I'll do them maybe in a followup PR)

Thank you!

**Comment by schloerke** [comment]
Closing in favor of https://github.com/rstudio/plumber/pull/862 which continues this PR

**Pull request closed without merging**
