### PR TITLE
Merged: type converters, dynamic image plots, dates/datetimes, open api object schema types, multiline comments, multipart form fix 

### PR DESCRIPTION
**Pull request by slodge**
This replaces the previous PRs on type converters, dynamic image plots, dates/datetimes and on open api object schema types - #897 #889 #891 #892 

If these changes were ever to go ahead, there's a heap of documentation and some tests to sort out... but that's for future consideration. 

Current manual test app:
```
#
# This is a Plumber API. You can run the API by clicking
# the 'Run API' button above.
#
# Find out more about building APIs with Plumber here:
#
#    https://www.rplumber.io/
#

devtools::load_all()

library(tidyverse)

#* @apiTitle Plumber Example API
#* @apiDescription Plumber example description.


#* Echo back the input
#* @param msg The message to echo
#* @get /echo
function(msg = "") {
  list(msg = paste0("The message is: '", msg, "'"))
}

#* Plot a histogram
#* @serializer png
#* @get /plot
function() {
  rand <- rnorm(100)
  hist(rand)
}

#* Return the sum of two numbers
#* @param a:int The first number to add
#* @param b:int The second number to add
#* @get /sum
function(a, b) {
  message("/sum processing a:", a, " of class ", class(a), " and b:", b, " of class ", class(b))
  a + b
}


#* Return the sum of two sets of numbers
#* @param a:[float] The first set of numbers to add
#* @param b:[float] The second set of numbers to add
#* @get /sumAll
function(a, b) {
  message("/sumAll processing a:", a, " of class ", class(a), " and b:", b, " of class ", class(b))
  sum(a, b)
}

#* Return a filtered set of strings
#* @param a:[logical] The filter map
#* @param b:[string] The set of string to filter
#* @get /filterText
function(a, b) {
  browser()
  message("/filterText processing a:", a, " of class ", class(a), " and b:", b, " of class ", class(b))
  b[a]
}

#* Is this working?
#* @param yes:bool Yes?
#* @get /boolTest
function(yes) {
  browser()
  if (yes) {
    "YES!"
  } else {
    "How sad.."
  }
}

#* @param when:date the date
#* @param t:date-time The date and time
#* @get /dates
function(when, t) {

  browser()
  paste0("The date was ", when, " and the time was ", t)
}

#* Do something
#* @post /doIt
#* @requestBody ARequestThing
#* @response 200 @body AResponseThing The success response
function(req) {
  browser()
  req$body
}

#* This is an object
#* @schema ARequestThing
#* @prop first:string The filter map
#* @prop a:[logical] The filter map
#* @prop b:[string] The set of string to filter
NULL

#* This is an object
#* @schema AResponseThing
#* @prop life:string Just a description
#* @prop details:[object]:AResponseSubThing This gets advanced
NULL

#* This is an object
#* @schema AResponseSubThing
#* @prop id:int Just a description
#* @prop value:string More descriptions
NULL

#* Plot out data from the iris dataset
#* @param spec If provided, filter the data to only this species (e.g. 'setosa')
#* @get /plot
#* @serializer png
function(spec = "setosa"){
  myData <- iris
  title <- "All Species"

  # Filter if the species was specified
  if (!missing(spec)){
    title <- paste0("Only the '", spec, "' Species")
    myData <- subset(iris, Species == spec)
  }

  plot(myData$Sepal.Length, myData$Petal.Length,
       main=title, xlab="Sepal Length", ylab="Petal Length")
}

#* Sort letters
#* @param letters:[string]
#* @serializer json
#* @get /letters/<letters:[string]>
function(letters) {
  sort(letters)
}
```

renders and runs as:
image

### CODE REVIEW

**Comment by taylo5jm** [comment]
@slodge Thanks for your work on the schemas -- I'm very interested in using this functionality. Is there a way to mark the schema properties as `required`? Also, anyone here able to give a general status update on this PR? I'm curious when these features might be available. Thanks!

**Comment by taylo5jm** [comment]
@slodge Awesome. The `*` works for me! 

Thanks for sharing the status of this PR. The "Schema Object" seems to be a useful component of the OpenAPI Specification (at least in version 3.1.0), so it would be great to see this functionality in `plumber`. 

@schloerke Are you able to provide more color around the issues blocking this PR in terms of timelines?

**Comment by slodge** [comment]
@schloerke @taylo5jm is there any kind of timeline for when someone at Posit might give plumber some attention? If we're waiting on "editions" before accepting new functionality, is there a design or draft PR for those so others can assist getting them built?

**Comment by JosiahParry** [comment]
I just wanted to follow up on this PR. It would be great to have.

**Comment by JosiahParry** [comment]
I suspect that this PR is too large to merge? Is there a suggested path forward for us to have argument type specification and parsing without having to manually cast inside the body of functions?

**Comment by slodge** [comment]
The team haven't had time to work on this nor on the previous smaller PRs -
but I do get periodic assurances they are keen to work on things and they
are hopeful to get something integrated soon.

From what they said before (December 2022) I think they want to implement a
new versioning scheme before they accept any new functionality - this seems
sensible, but I don't know any timeline on that.

You can still see the smaller PRs in closed PRs here - your welcome to
reinstate them, but I'd check with posit on their availability and plans
before investing too much effort 👍

Alternatively, it looks increasingly like FastApi might be a good route to
consider - that has ongoing development and good support in Connect.

**Comment by JosiahParry** [comment]
@slodge thanks! FastAPI is a python library and out of scope of my interest :)

**Comment by slodge** [comment]
I think this is the smaller PR you are interested in -
https://github.com/rstudio/plumber/pull/889

We closed it because it was too much effort maintaining multiple
long-running feature branches for us internally.

**Comment by slodge** [comment]
Notes from https://github.com/rstudio/plumber/issues/911 also merged

**Comment by slodge** [comment]
As discussed in #920 this PR is too large and complex to merge.

Respectfully closing.

**Pull request closed without merging**
